name: Build (master)
on: push
#  push:
#    branches:
#      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 2
      - name: Setup node
        uses: actions/setup-node@master
        with:
          node_version: 12.x

