name: 'Build (master)'
on:
  push:
    branches: master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 2
      -
        name: 'Get branch name'
        uses: ./.github/actions/parse-gk-lockfile-vars
        id: bname
      -
        name: 'Setup node'
        uses: actions/setup-node@master
        with:
          node-version: 12.x
      -
        name: 'Set default origin'
        run: 'git config --local checkout.defaultRemote origin'
      -
        name: 'Install GK lockfile'
        run: 'npm install -g github:Alorel/greenkeeper-lockfile#390c7def6e8c01989763c2391e66f12f60f9a185'
      -
        name: 'Update GK lockfile'
        env:
          GK_LOCK_GENERIC_CI: 'true'
          GK_LOCK_GENERIC_CI_REPO_SLUG: '${{ github.repository }}'
          GK_LOCK_GENERIC_CI_BRANCH_NAME: '${{ steps.bname.outputs.branchName }}'
          GK_LOCK_GENERIC_CI_FIRST_PUSH: 'false'
          GK_LOCK_GENERIC_CI_CORRECT_BUILD: 'true'
          GK_LOCK_GENERIC_CI_UPLOAD_BUILD: 'false'
          GH_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        run: greenkeeper-lockfile-update
      -
        name: 'npm install'
        run: 'npm install'
      -
        name: 'Upload GK lockfile'
        env:
          GK_LOCK_GENERIC_CI: 'true'
          GK_LOCK_GENERIC_CI_REPO_SLUG: '${{ github.repository }}'
          GK_LOCK_GENERIC_CI_BRANCH_NAME: '${{ steps.bname.outputs.branchName }}'
          GK_LOCK_GENERIC_CI_FIRST_PUSH: 'false'
          GK_LOCK_GENERIC_CI_CORRECT_BUILD: 'true'
          GK_LOCK_GENERIC_CI_UPLOAD_BUILD: 'false'
          GH_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        run: greenkeeper-lockfile-upload
